version: '3.1'

services:
    service:
        container_name: port-service
        restart: always
        build: ./bin/service
        ports:
            - '8080'
        volumes:
            - ./config.env:/root/config.env
        links:
            - mongo

    mongo:
        container_name: port-mongo
        restart: always
        build:
            context: ./bin/mongodb
        volumes:
            - /etc/timezone:/etc/timezone:ro
        ports:

            - '27017'
networks:
  default:
    name: portnetwork