version: '3.1'

services:
    service:
        restart: always
        build: ./bin/service
        ports:
            - '80:8080'
        environment:
          MONGO_CONNECT: '${MONGO_CONNECT}'
          SymmetricKey: '${SymmetricKey}'
        links:
            - mongo

    mongo:
        container_name: mongo
        build:
            context: ./bin/mongodb
        volumes:
            - /etc/timezone:/etc/timezone:ro
        ports:
            - '27017:27017'
