version: '3.1'

services:
    service:
        restart: always
        build: ./bin/service
        ports:
            - '8081:8080'
        volumes:
            - ./config.env:/root/config.env
        links:
            - mongo

    mongo:
        container_name: mongo
        build:
            context: ./bin/mongodb
        volumes:
            - /etc/timezone:/etc/timezone:ro
        ports:
            - '27017:27017'